api_platform:
  title: Ma super app de gestion de tickets
  version: 1.0.0
  show_webby: false
  # Good defaults for REST APIs
  swagger:
    api_keys:
      myAuth:
        name: Authorization
        type: header
  defaults:
    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
    extra_properties:
      standard_put: true
